services:
  - type: web
    name: datinghub2026
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn datinghub.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: datinghub_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: datinghub2026.onrender.com
      - key: BREVO_API_KEY
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: recommendations@datinghub2026.com
      - key: EMAIL_HOST
        value: smtp-relay.brevo.com
      - key: EMAIL_PORT
        value: 587

databases:
  - name: datinghub_db
    plan: free
